### ISSUE TITLE
Music System

### ISSUE THREAD

**Issue by thezeeone** [Zahid556/ZBot-En#16]
**__CANCELLED. PULL REQUEST CLOSED. HEAD TO [THIS DISCORD MESSAGE](https://discord.com/channels/1000073833551769600/1000079781041275080/1005765650398060664) FOR MORE INFORMATION.__**

**Comment by thezeeone** [comment]
enhancement bc new system

**Comment by thezeeone** [comment]
if I can I will try to add spotify support for y'all spotify fans 😃

**Comment by thezeeone** [comment]
Start with VSC testing for `/play` and `/leave` before we even support a queue system

See latest commits

**Comment by thezeeone** [comment]
Add command imports

**Comment by thezeeone** [comment]
For now imma just allow youtube support until I find a package that supports spotify

**Comment by thezeeone** [comment]
Testing regex for youtube links

__TEST CASES__
```
https://www.youtube.com/watch?v=DFYRQ_zQ-gk&feature=featured
https://www.youtube.com/watch?v=DFYRQ_zQ-gk
http://www.youtube.com/watch?v=DFYRQ_zQ-gk
//www.youtube.com/watch?v=DFYRQ_zQ-gk
www.youtube.com/watch?v=DFYRQ_zQ-gk
https://youtube.com/watch?v=DFYRQ_zQ-gk
http://youtube.com/watch?v=DFYRQ_zQ-gk
//youtube.com/watch?v=DFYRQ_zQ-gk
youtube.com/watch?v=DFYRQ_zQ-gk
https://m.youtube.com/watch?v=DFYRQ_zQ-gk
http://m.youtube.com/watch?v=DFYRQ_zQ-gk
//m.youtube.com/watch?v=DFYRQ_zQ-gk
m.youtube.com/watch?v=DFYRQ_zQ-gk
https://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
http://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
//www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US
https://www.youtube.com/embed/DFYRQ_zQ-gk?autoplay=1
https://www.youtube.com/embed/DFYRQ_zQ-gk
http://www.youtube.com/embed/DFYRQ_zQ-gk
//www.youtube.com/embed/DFYRQ_zQ-gk
www.youtube.com/embed/DFYRQ_zQ-gk
https://youtube.com/embed/DFYRQ_zQ-gk
http://youtube.com/embed/DFYRQ_zQ-gk
//youtube.com/embed/DFYRQ_zQ-gk
youtube.com/embed/DFYRQ_zQ-gk
https://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk?autoplay=1
https://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
http://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
//www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
www.youtube-nocookie.com/embed/DFYRQ_zQ-gk
https://youtube-nocookie.com/embed/DFYRQ_zQ-gk
http://youtube-nocookie.com/embed/DFYRQ_zQ-gk
//youtube-nocookie.com/embed/DFYRQ_zQ-gk
youtube-nocookie.com/embed/DFYRQ_zQ-gk
https://youtu.be/DFYRQ_zQ-gk?t=120
https://youtu.be/DFYRQ_zQ-gk
http://youtu.be/DFYRQ_zQ-gk
//youtu.be/DFYRQ_zQ-gk
youtu.be/DFYRQ_zQ-gk
```

**Comment by thezeeone** [comment]
Regex created
`/(?:(?:https?:)?\/\/)?(?:(?:www\.|m\.)?youtu\.?be(?:-nocookie)?(?:\.com)?)\/(?:(?:watch\?v=|embed\/|v\/)?([\w\d-]+))/`

**Comment by thezeeone** [comment]
Updates the links as those that start with `//`, although lead to a URL, do not match the proper format and thus will be rejected by the bot.
Also you can only have one link at a time and no longer have multiple. `g` flag not used but `m` is, to get the actual video ID.

**New RegEx**
`/^(?:https?:\/\/)?(?:(?:www\.|m\.)?youtu\.?be(?:-nocookie)?(?:\.com)?)\/(?:(?:watch\?v=|embed\/|v\/)?([\w\d-]+))$/`

`#00ff00` **Valid Links**
`https://www.youtube.com/watch?v=DFYRQ_zQ-gk&feature=featured`
`https://www.youtube.com/watch?v=DFYRQ_zQ-gk`
`http://www.youtube.com/watch?v=DFYRQ_zQ-gk`
`www.youtube.com/watch?v=DFYRQ_zQ-gk`
`https://youtube.com/watch?v=DFYRQ_zQ-gk`
`http://youtube.com/watch?v=DFYRQ_zQ-gk`
`youtube.com/watch?v=DFYRQ_zQ-gk`
`https://m.youtube.com/watch?v=DFYRQ_zQ-gk`
`http://m.youtube.com/watch?v=DFYRQ_zQ-gk`
`m.youtube.com/watch?v=DFYRQ_zQ-gk`
`https://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US`
`http://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US`
`www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US`
`youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US`
`https://www.youtube.com/embed/DFYRQ_zQ-gk?autoplay=1`
`https://www.youtube.com/embed/DFYRQ_zQ-gk`
`http://www.youtube.com/embed/DFYRQ_zQ-gk`
`www.youtube.com/embed/DFYRQ_zQ-gk`
`https://youtube.com/embed/DFYRQ_zQ-gk`
`http://youtube.com/embed/DFYRQ_zQ-gk`
`youtube.com/embed/DFYRQ_zQ-gk`
`https://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk?autoplay=1`
`https://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`http://www.youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`www.youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`https://youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`http://youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`https://youtu.be/DFYRQ_zQ-gk?t=120`
`https://youtu.be/DFYRQ_zQ-gk`
`http://youtu.be/DFYRQ_zQ-gk`
`youtu.be/DFYRQ_zQ-gk`

`#ff0000` **Invalid Links**
`//youtu.be/DFYRQ_zQ-gk`
`//youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`//www.youtube.com/embed/DFYRQ_zQ-gk`
`//www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US`
`//www.youtube-nocookie.com/embed/DFYRQ_zQ-gk`
`//www.youtube.com/watch?v=DFYRQ_zQ-gk`
`//youtube.com/watch?v=DFYRQ_zQ-gk`
`//youtube.com/embed/DFYRQ_zQ-gk`
`//m.youtube.com/watch?v=DFYRQ_zQ-gk`

**Comment by thezeeone** [comment]
to store the video files, we need a new folder for YTDL to `.pipe()` it to before we can create an audio resource and start playing the audio

**Comment by thezeeone** [comment]
Testing

**Comment by thezeeone** [comment]
Several errors occuring, might have to remake the command

**Comment by thezeeone** [comment]
close to fixing problem on VSC

**Comment by Zahid556** [comment]
إضافة تفاصيل الفيديو

**Comment by thezeeone** [comment]
Add video details
(commented in wrong git repository)

**Comment by thezeeone** [comment]
![image](https://user-images.githubusercontent.com/76518130/182844540-a0306ae0-4579-499f-9072-d64f76ec4cd9.png)
![image](https://user-images.githubusercontent.com/76518130/182844594-f6cc2ebd-d3e6-470a-8e1c-6e711f7218c9.png)
![image](https://user-images.githubusercontent.com/76518130/182844646-aeca0b6c-63d0-48d6-ae5d-3bdd4e84b107.png)
![image](https://user-images.githubusercontent.com/76518130/182844745-4d0259d9-ca31-428f-9b15-11b66dfe13f2.png)
interesting

**Comment by thezeeone** [comment]
next tasks: 
* `/stop`
* `/leave`
* `/pause`
* queue system

**Comment by thezeeone** [comment]
(removed `.setThumbnail()` because it was throwing errors for some reason)

**Comment by Zahid556** [comment]
work on leave command

**Comment by thezeeone** [comment]
nevermind, will work on queue system

**Comment by thezeeone** [comment]
Accidentally closed
Will test later

**Comment by thezeeone** [comment]
Support for per-server queue system available, however there are a couple of issues that I am trying to resolve rn

**Comment by thezeeone** [comment]
Testing

**Comment by thezeeone** [comment]
Add condition to check if there's already a song playing in the queue
