### ISSUE TITLE
Economy system

### ISSUE THREAD

**Issue by zr0D4Y** [Zahid556/ZBot-En#18]
Extra criteria:
BlackList commands for admins
anti macros
Real estate could be an option 
Weapons increasing chances of loot when robbing

**Comment by thezeeone** [comment]
Criteria:
* XP exchangable for coins.
* Wallet and Bank system.
* Bank can increase every time a member levels up.
* Currency: ZCoin Symbol: Z + discord coin symbol
* Bank robbery where users if not caught by chance can rob off of others
* A couple simple shop systems

**Comment by thezeeone** [comment]
once all commands are fixed and source code updated

**Comment by zr0D4Y** [comment]
pepe

**Comment by zr0D4Y** [comment]
We also need a way to increase the amount of coins so the game gets harder over time; I feel like we should add a system where if we refresh the coins, we use the old coins that were grinded and then give them out so that the big amount becomes smaller every refresh

**Comment by thezeeone** [comment]
I already have a blacklist command

**Comment by thezeeone** [comment]
**THIS PROJECT WILL BE SPLIT INTO PHASES**

**__PHASE `1`__** *Discussion*
**Current Phase**
This is where we gather all our ideas together and decide on what we can add and what not. 

**__PHASE `2`__** *Development*
This is where we implement the ideas into the bot.

**__PHASE `3`__** *Testing*
This is where we test all the features to see if they work. Phase 2 and 3 may intersect at some points, for example, testing a feature right after it is added.

**Comment by thezeeone** [comment]
@zr0D4Y ngl that is a good idea but how much would we decrease that by?

**Comment by thezeeone** [comment]
also which weapons could we potentially add

**Comment by thezeeone** [comment]
if we have a weapon... we could also consider the potential chances that weapon has of increasing robbery. for example, knife ain't that much good against a bomb. also we would have to consider damage the bank takes with these weapons, for example a bomb could potentially mean either loss of most/all money or robbery

**Comment by thezeeone** [comment]
i think we should leave this open to discussion for the server

**Comment by thezeeone** [comment]
but first we should get on the issues i mentioned in [#zbot-announcements](https://discord.com/channels/1000073833551769600/1000079781041275080/1010539873675005952 'Errors to be fixed for the final ZBot command-by-command update - click here to jump to the Discord message')

**Comment by thezeeone** [comment]
almost done fixing issues

**Comment by thezeeone** [comment]
source code updated

**Comment by zr0D4Y** [comment]
hello, sorry i've been dying. This is a good plan. A few weapons we could add?
Knife starter weapon
Z shank exclusive item that only u have
sword
rifle 
ak47 only attainable from quiet kid

**Comment by zr0D4Y** [comment]
Ok so, we will take the coins the players grind and give it out again equally so they grind more money than before and therefore the amount of money in the economy gets large

**Comment by thezeeone** [comment]
would be cool but how would we do that

**Comment by zr0D4Y** [comment]
helloooo
this would probs have to be done manually by counting up their coins and editing the code

**Comment by thezeeone** [comment]
i'm gonna start with the code that i'm currently updating rn on vsc

**Comment by zr0D4Y** [comment]
yessir

**Comment by thezeeone** [comment]
convert code to TS?

**Comment by thezeeone** [comment]
wait what have u added so far

**Comment by zr0D4Y** [comment]
Simple balance nothing advanced
store
trade
inventory 
planning to add beg petshop and z1store

**Comment by thezeeone** [comment]
ok so i'll decide on making a command so the user can check their balance etc

**Comment by thezeeone** [comment]
im thinking we should also allow users to exchange zcoins
ill also try and think of a system where u can switch between bank and wallet and yea

**Comment by thezeeone** [comment]
then once we're done we'll just do a simple shop system nothing advanced 
im also thinking we should add 20% and 50% 24-hour XP boosts for the prices of 200 coins and 500 coins respectively

**Comment by thezeeone** [comment]
or the prices can vary

**Comment by zr0D4Y** [comment]
ive already added a balance command and user exchange, and im working on user multipliers
but yes those features have been added already,

**Comment by thezeeone** [comment]
just need to add those to my bot

**Comment by thezeeone** [comment]
what shall we name them, "withdraw" for wallet > bank and "depo"/"deposit" for bank > wallet?

**Comment by zr0D4Y** [comment]
yeah the file i uploaded has everything, have u finished converting?

**Comment by zr0D4Y** [comment]
for now all i have is one balance for the entire user and im working on a wallet and bank in my seperate copy

**Comment by thezeeone** [comment]
not gonna bother converting so i'll just add to my current branch which is now deleted but im still on weirdly
and then we'll test it bit by bit

**Comment by zr0D4Y** [comment]
aight thats fine

**Comment by zr0D4Y** [comment]
when we gonna try teh first ttime

**Comment by thezeeone** [comment]
when i fix issues with my member-info command and then we can move on

**Comment by zr0D4Y** [comment]
k

**Comment by thezeeone** [comment]
ok lemme start working on the balance command first
and then the withdraw command
and then the depo command

**Comment by zr0D4Y** [comment]
are we gonna use the code i sent or we going from scratch?

**Comment by thezeeone** [comment]
let's see the code you sent

**Comment by zr0D4Y** [comment]
eco branch in fuck

**Comment by thezeeone** [comment]
gonna check

**Comment by thezeeone** [comment]
empty 😂

**Comment by zr0D4Y** [comment]
HUHUHU

**Comment by thezeeone** [comment]
ok its fine i'll start from scratch

**Comment by zr0D4Y** [comment]
fuckkk

**Comment by zr0D4Y** [comment]
all that for nothin

**Comment by thezeeone** [comment]
normal slash command with no options right?

**Comment by zr0D4Y** [comment]
ok i guess
what commands should i work on?

yes

**Comment by zr0D4Y** [comment]
should i do a shop?

**Comment by thezeeone** [comment]
didnt you say you have a couple of shops set up

**Comment by zr0D4Y** [comment]
in my source file 
but apparently u cannot find them so we are gonns start from scratch u said?
i can shoow u on discord whre it is

**Comment by thezeeone** [comment]
if you wanna work on the shops then do so because i'll get the basics ready first
which are
- [ ] balance
- [ ] deposit
- [ ] withdraw
- [ ] give (for giving coins to other members)

**Comment by thezeeone** [comment]
right now im working on balance

**Comment by zr0D4Y** [comment]
aight then ill try to recreate the shops in my old files, please post all variable names u use

**Comment by thezeeone** [comment]
yea

**Comment by zr0D4Y** [comment]
ill probably need the wallet variable name 
and ill handle inventory ig

**Comment by thezeeone** [comment]
ive decided to add to the command an option where u can check a users balance and it gonna be optional

**Comment by zr0D4Y** [comment]
oh yeah, ill add that to the inv command

**Comment by thezeeone** [comment]
ok

**Comment by thezeeone** [comment]
wait how are you gonna store the inventory of a user

**Comment by thezeeone** [comment]
because since I'm using PostgreSQL i have the ability to store arrays (hopefully)

**Comment by zr0D4Y** [comment]
oh was gonna use collections

**Comment by thezeeone** [comment]
the user's inventory can very, some have cups of tea others only chocolate some both and you can't just list every single item in the model and store them as an integer when we can have an array of objects to represent what the user has

**Comment by thezeeone** [comment]
we can give each item an identifier lol

**Comment by thezeeone** [comment]
then store them by their identifier and amount

**Comment by thezeeone** [comment]
afk

**Comment by zr0D4Y** [comment]
ok arrays it is

ill add my commands to the commands folder in this branch and leave the variable and such for u to fill

**Comment by thezeeone** [comment]
back

**Comment by zr0D4Y** [comment]
my other files used collections

**Comment by thezeeone** [comment]
collections as discord.js stated is only for things with unique IDs
so for example a collection of users
but for other things such as embeds they use arrays

**Comment by thezeeone** [comment]
technically we _might_ have identifiers so we could make our products uniquely different so a collection could be good use here

**Comment by thezeeone** [comment]
but for now i'll stick to arrays

**Comment by thezeeone** [comment]
done with balance cmd

**Comment by thezeeone** [comment]
now i need to do withdraw and deposit commands which are fairly easy

**Comment by thezeeone** [comment]
deposit command done
will copy code over to and edit withdraw command

**Comment by thezeeone** [comment]
almost done

**Comment by thezeeone** [comment]
gonna be testing now

**Comment by zr0D4Y** [comment]
sorry but will be taking a bit of time as have to help me mom

**Comment by thezeeone** [comment]
oops i think i lost my economymodel lmao
nw I'll try recreate it again

**Comment by thezeeone** [comment]
recreated

**Comment by Zahid556** [comment]
what do you think the syntax should be for users etc?

shall we use curly braces or something? `{user}` `{server}`

also i'm deciding on the information we can post eg user creation date tag username new member count server etc

**Comment by thezeeone** [comment]
(sorry commented in wrong place)

**Comment by thezeeone** [comment]
will convert ur code to ts soon

**Comment by thezeeone** [comment]
ok im part of the way thru welcome system editor so i'll temporarily close this as not planned then once im done i will re-continue the system

**Comment by thezeeone** [comment]
Temporarily closed until further notice.

**Comment by thezeeone** [comment]
reopened

**Comment by thezeeone** [comment]
ngl imagine this passes 100 comments rn

**Comment by thezeeone** [comment]
since I haven't worked on this for so long I'll merge the WMEM branch first since that's got all the new features and then I'll get working straightaway on the economy system

**Comment by thezeeone** [comment]
that closure was an accident

**Comment by zr0D4Y** [comment]
finally back, adding a safe and upgrade safe, hopefully
please discuss the properties of a safe.

**Comment by thezeeone** [comment]
Ykw gonna merge the branch for this before I proceed to work on the new issues + economy system 2.0

**Comment by thezeeone** [comment]
We have a simple betting system so that's cool

**Comment by thezeeone** [comment]
Gonna open PR for this meanwhile create few more issues

**Comment by thezeeone** [comment]
Closed

**Comment by thezeeone** [comment]
If you have any new ideas move it into the new issue

**Comment by ZahidGoofy123** [comment]
ok brother i have the chakne

**Comment by ZahidGoofy123** [comment]
japkelelelellelelelel
HO

**Comment by ZahidGoofy123** [comment]
btw i am half blod
