### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by waxy79** [Zahid556/ZBot-En#19]
The bot stays stuck on loading if I run for example /ban or /rank in other servers, is there a issue or is the bot down.

**Comment by thezeeone** [comment]
can u please explain what the issue is in a bit more detail
eg
when does it happen
does the bot reply, stay loading or not reply at all

**Comment by waxy79** [comment]
It stays loading, and it fails or doesn't respond at all, and if I chat or something it sometimes doesn't count the xp and just stays at the same number.

**Comment by thezeeone** [comment]
ok i'm going to experiment with it a little bit to see

**Comment by thezeeone** [comment]
does the bot just go down straight after you run the command

**Comment by thezeeone** [comment]
that's a strange issue tbh. it has never happened in our own support server with the exception of trying to run the leaderboard command with `Display global leaderboard` and it just loading for **aaages** before throwing an error but still running
are you sure it happens in only the server you've tried to run it in? if it is then try kick the bot out before adding it again
you can invite me to the server in DMs if that helps

**Comment by thezeeone** [comment]
i think this issue is resolved

**Comment by thezeeone** [comment]
reopened

**Comment by thezeeone** [comment]
we're still trying to resolve a couple issues with the bot @waxy79 i've mentioned in a recent issue:
> ⚠**Warning: this is an experimental feature and may break while in use, please use this command __at the bot's own risk__.**
> Some buttons, select menus or features may fail, cause the command to behave strangely, or even worse, cause the bot to crash entirely. If using this command, we advise you use this **at the bot's own risk.**

also soon i might start adding warning messages to say that the command is experimental before proceeding

**Comment by thezeeone** [comment]
which commands is it specifically

**Comment by waxy79** [comment]
Like /rank/leaderboard and /kick

**Comment by waxy79** [comment]
My friend in a server has he the bot and he tried to kick a member but it didn't work and lb

**Comment by thezeeone** [comment]
/rank and /leaderboard take some time to load because the leaderboard is massive

**Comment by thezeeone** [comment]
we literally have a massive database of more than 85 users who each have their levels and XP stored so to try and sort all of that out is chaos
but whats with the `/kick` command, give more detail about it

**Comment by thezeeone** [comment]
> My friend in a server has he the bot and he tried to kick a member but it didn't work and lb

when did you run these commands? and what does he mean by "doesn't work"

**Comment by waxy79** [comment]
It says reaction failed or command didn't work

**Comment by thezeeone** [comment]
can u invite him to my server, for more detail
"didn't work" doesn't seem to help me with anything

**Comment by waxy79** [comment]
He means it didn't work like the kick didn't work

**Comment by thezeeone** [comment]
ok so ask him step-by-step what he did with the command and where it went wrong

**Comment by waxy79** [comment]
So there was a guy who was spamming in his server so he did /kick and he clicked yes but the bot did no and it failed

**Comment by thezeeone** [comment]
so you're saying when he clicked yes the bot took it for a no and the command then failed?

**Comment by thezeeone** [comment]
did he reply within the timeout? the timeout is 2 minutes, that's the time he has to reply before the command fails

**Comment by thezeeone** [comment]
if you can please invite him to my server bc its getting difficult to understand this

**Comment by thezeeone** [comment]
i think i get the issue now, it comes across all moderation commands when you press any `No` button
i'll get fixing on that

**Comment by thezeeone** [comment]
during my testing with the welcome editor

**Comment by thezeeone** [comment]
have a go at the commands again and let me know if they work @waxy79

**Comment by thezeeone** [comment]
Temporarily closed until further notice.

**Comment by thezeeone** [comment]
reopened
