### ISSUE TITLE
Per-Server Welcome System Editor

### ISSUE THREAD

**Issue by thezeeone** [Zahid556/ZBot-En#20]
Allow a per-server welcome system editor which is basically an editor which can be run from one command and you have the entire interface in front of you.
Requires member to have manage server permission.
Welcome system in DM messages not allowed.
User can choose a bunch of options eg discard / save changes  /  edit / add / remove stuff
then from there they can have a select menu where they choose what to add / remove etc

**Comment by zr0D4Y** [comment]
Button interface or what?

**Comment by thezeeone** [comment]
yea, button interface

**Comment by thezeeone** [comment]
i've partially started it off
i'm going to branch it off of the economy system branch so I don't lose both my changes

**Comment by thezeeone** [comment]
ive already defined my model 
```ts
interface WelcomeMessageEditorModel extends Model<InferAttributes<WelcomeMessageEditorModel>, InferCreationAttributes<WelcomeMessageEditorModel>> {
    id: string,
    message?: string,
    embeds?: APIEmbed
}
```

**Comment by zr0D4Y** [comment]
oh yeah i'm still gonna code the z bot site

**Comment by thezeeone** [comment]
commited change
shit, forgot to mention this issue in the description

**Comment by thezeeone** [comment]
ok nice but are you gonna be able to host it

**Comment by zr0D4Y** [comment]
just make it simple tbh just add a basic hello, go check out {channelId}, {user.tag}

**Comment by thezeeone** [comment]
yea

**Comment by thezeeone** [comment]
while im coding I'll think of the syntax we should use if the user wants to customise it in their own way

**Comment by zr0D4Y** [comment]
i prolly won't be able to host it cuz my laptops loud but if i send the code on github u could host at the same time and z bot or we could find free hosting

**Comment by thezeeone** [comment]
maybe but issue with free hosting is it's probably temporary and won't be good

**Comment by thezeeone** [comment]
i think we should start funding this project because it's quite good. already in 15 servers keeping an eye on 271 users and without hosting options it would be rubbish

but for now let's keep the topic related to this issue's title

**Comment by zr0D4Y** [comment]
better than nothing tbh plus if it's only on when zbot is that's probably fine

**Comment by zr0D4Y** [comment]
cool i'll code the website anyways tho cuz i don't have anything else to do and post the code when u want it

**Comment by thezeeone** [comment]
ok i'll let you know what you think of it 
for now i'm going to define that model as a table in sequelize and will start making my command
i literally have an empty ts module sitting there

**Comment by thezeeone** [comment]
ts makes my life with modules so much easier

**Comment by thezeeone** [comment]
gonna make a commit once im done with defining and exporting

**Comment by thezeeone** [comment]
this looks good 
```ts
const WelcomeMessageEditorModel = sequelize.define<WelcomeMessageEditorModel>('WMEditors', {
    id: {
        type: DataTypes.STRING,
        primaryKey: true
    },
    message: {
        type: DataTypes.STRING,
        defaultValue: ''
    },
    embeds: {
        type: DataTypes.ARRAY(DataTypes.JSON),
        defaultValue: []
    }
})
```

**Comment by thezeeone** [comment]
ok gonna export and make a first commit for this

**Comment by thezeeone** [comment]
now imma make the file and we'll see how it gets

**Comment by thezeeone** [comment]
in the meanwhile i'll edit the code in this new branch imma create so I can switch _for **once** in my life_

**Comment by thezeeone** [comment]
what do you think the syntax should be for users etc?

shall we use curly braces or something? `{user}` `{server}`

also i'm deciding on the information we can post eg user creation date tag username new member count server etc

(sorry posted this in #18 by accident)

**Comment by thezeeone** [comment]
i have an empty file i havent worked on for ages now 😂😂😂

**Comment by thezeeone** [comment]
ok gon start working on a basic version, that includes interactive buttons, a bit of syntax `{user.id}` `{user.username}` `{user.discriminator}` `{user.tag}` `{server.name}` `{server.id}`
(let's not forget the most important, `{user.mention}`)

**Comment by thezeeone** [comment]
i'll have the `#0f0` `[Save]`, `#f00` [Discard] and `[Edit]` and `[Preview]` buttons

**Comment by thezeeone** [comment]
for now we'll have a basic message although there's already embeds defined however its default value is an empty embed
and in the meanwhile I'm going to test it out to see how it goes

**Comment by thezeeone** [comment]
also I forgotten but I'll add a setting where you can enable and disable it

**Comment by thezeeone** [comment]
only later will i worry about embeds; for now I'll keep it simple (because embeds are complicated and will require a lot)

**Comment by thezeeone** [comment]
syncing changes to github

**Comment by thezeeone** [comment]
made a couple commits so far but it's not complete

**Comment by zr0D4Y** [comment]
yes very good, are we gonna start the tickets

**Comment by thezeeone** [comment]
open a separate issue for that

**Comment by thezeeone** [comment]
imma continue working on this while you get a basic version of the ticket setup

**Comment by thezeeone** [comment]
ok i should have staged changes by now

**Comment by thezeeone** [comment]
gonna sync changes

**Comment by thezeeone** [comment]
if this editor is successful, then watch every editor after this become successful too
see, the requests to accept or deny games with opponents worked out pretty well (even though there are still quite a few errors with some)

**Comment by thezeeone** [comment]
gonna quickly test it before I jump across to issue #22

**Comment by thezeeone** [comment]
now this command just isn't gonna respond AT ALL

**Comment by thezeeone** [comment]
found a solution, i have an if statement without an else statement

**Comment by thezeeone** [comment]
fixed. will work on vote command first then get back to this

**Comment by thezeeone** [comment]
the enabling-disabling will change soon
but also i will bring functionality to each of the buttons hopefully

**Comment by thezeeone** [comment]
i've given the enable and disable function a bit of functionality and hopefully it should work

**Comment by thezeeone** [comment]
lmao broken, just says interaction failed

**Comment by thezeeone** [comment]
idk why but ffs every time I do a case statement it doesn't respond yet everytime I do an if else if else chain it works fine

**Comment by thezeeone** [comment]
ok switched to if-else/if-else now im going to test it while updating

**Comment by thezeeone** [comment]
i'm now going to give the edit button a functionality, before proceeding to add save and discard button functionalities

**Comment by thezeeone** [comment]
i'll also think of giving the channel and preview buttons functionality, but most importantly I'll just continue with the edit button

discard and save buttons need functionality 

and enable/disable buttons need to actually do some action

**Comment by thezeeone** [comment]
Temporarily closed until further notice.

**Comment by thezeeone** [comment]
reopened

**Comment by thezeeone** [comment]
am now gonna continue working on this

**Comment by thezeeone** [comment]
80% of the way through lesgooo

**Comment by thezeeone** [comment]
just when I finish the code and test it i'll make a PR for this

**Comment by thezeeone** [comment]
done
