### ISSUE TITLE
Ticket system

### ISSUE THREAD

**Issue by zr0D4Y** [Zahid556/ZBot-En#21]
go brr

**Comment by thezeeone** [comment]
brr

**Comment by thezeeone** [comment]
i'll start off by making it a local system, within our support server only

while I continue working on the welcome system

**Comment by thezeeone** [comment]
give me a couple ideas we could have

**Comment by zr0D4Y** [comment]
hmm, new channels opened for issues with only staff and the reporter, closing and opening channel, message deletion in those channels unless bot command

**Comment by zr0D4Y** [comment]
YES MY COD

**Comment by thezeeone** [comment]
> hmm, new channels opened for issues with only staff and the reporter, closing and opening channel, message deletion in those channels unless bot command

good idea @zr0D4Y but will keep it to staff only

**Comment by zr0D4Y** [comment]
like only staff can and the reporter can use the reported channel?

**Comment by thezeeone** [comment]
yea, I'll say all staff for now

**Comment by thezeeone** [comment]
allow the trainees as well so they can practise

**Comment by thezeeone** [comment]
and maybe soon we'll bring a feature to ZBot where u can apply for staff and practise training

**Comment by zr0D4Y** [comment]
hm yes

**Comment by thezeeone** [comment]
bc the staff rn need a bit of training so we bring a use to it

**Comment by zr0D4Y** [comment]
we could just use a simple microsoft forms link for a command like /staff application that u can only do if ur level is above or the staff application level

**Comment by thezeeone** [comment]
i don't like microsoft forms, people can easily fill out the form, lie about their level / personal details etc

**Comment by thezeeone** [comment]
while yes we can have the `/staff` command, that would be a good idea, i would prefer having the application done through `/staff`

**Comment by zr0D4Y** [comment]
They cannot lie about levels if the command of only unlocks at a certain level and the link is show user only

**Comment by zr0D4Y** [comment]
hm alr ig u could always use buttons and shit

**Comment by thezeeone** [comment]
or u can always have pre-defined checks such as what's with the moderation commands

**Comment by thezeeone** [comment]
Temporarily closed until further notice.

**Comment by thezeeone** [comment]
reopened

**Comment by thezeeone** [comment]
it's been only 15 hours now

**Comment by thezeeone** [comment]
im already 75% of the way through
@zr0D4Y

**Comment by thezeeone** [comment]
lesgooo it worked @zr0D4Y
