### ISSUE TITLE
Complete removal of the ticket system

### ISSUE THREAD

**Issue by thezeeone** [Zahid556/ZBot-En#31]
Pretty much the same reasons as removal of PSWMEs

**Comment by ZahidGoofy123** [comment]
I got a problem
Top G ( Half Blood) doesnt have his roles
can you give him back

**Comment by thezeeone** [comment]
**Criteria**

- [ ] Removal of [`index.ts:L208-L540`](https://github.com/thezeeone/ZBot-En/blob/WMEM-branch/index.ts#L208-L540)
- [ ] Complete removal of [`commands/report-member.ts`](https://github.com/thezeeone/ZBot-En/blob/WMEM-branch/commands/report-member.ts), [`commands/report-message.ts`](https://github.com/thezeeone/ZBot-En/blob/WMEM-branch/commands/report-message.ts) and [`commands/ticket.ts`](https://github.com/thezeeone/ZBot-En/blob/WMEM-branch/commands/report-member.ts) files
- [ ] Removal of imports in [`commands/command-exports.ts`](https://github.com/thezeeone/ZBot-En/blob/WMEM-branch/commands/command-exports.ts) and [`index.ts`](https://github.com/thezeeone/ZBot-En/blob/WMEM-branch/index.ts)
